# Compose file for running app locally with a local Postgres container
services:

    db:
        image: postgres:latest
        container_name: postgres
        restart: unless-stopped

        environment:
          POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

        ports:
          - 5432:5432

        volumes:
          - ./instance/postgres:/var/lib/postgresql/data

        secrets:
          - postgres_password

secrets:
  postgres_password:
    file: ./secrets/POSTGRES_PASSWORD