# Compose file for running app locally with a local Postgres container
services:

    db:
        image: postgres:latest
        container_name: apidb
        restart: unless-stopped

        environment:
          POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

        ports:
          - 5432:5432

        volumes:
          - ./instance/postgres:/var/lib/postgresql/data

        secrets:
          - postgres_password

    flaskapi:
        build:
          dockerfile: Dockerfile
        container_name: flaskapi
        restart: unless-stopped
        command: ["sh", "-c", "flask run --host 0.0.0.0"]     # Run without gunicorn locally

        volumes:
            - ./:/app

        environment:
            JWT_SECRET_KEY_FILE: /run/secrets/jwt_secret_key
            MAILGUN_DOMAIN_FILE: /run/secrets/mailgun_domain
            MAILGUN_API_KEY_FILE: /run/secrets/mailgun_api_key

        ports:
          - 5000:5000

        secrets:
          - jwt_secret_key
          - mailgun_api_key
          - mailgun_domain


secrets:
  jwt_secret_key:
    file: ./secrets/JWT_SECRET_KEY
  postgres_password:
    file: ./secrets/POSTGRES_PASSWORD
  mailgun_domain:
    file: ./secrets/MAILGUN_DOMAIN
  mailgun_api_key:
    file: ./secrets/MAILGUN_API_KEY