#!/usr/bin/env bash
METHOD=$(cat $1 | (jq ".requests[] | select(.name == \"$2\").method") | sed --expression 's/\"//g')
URL=$(cat $1 | (jq ".requests[] | select(.name == \"$2\").url") | sed --expression 's/\"//g' | sed --expression 's/{{/{{$dotenv %/g')
HEADERS=$(cat $1 | (jq ".requests[] | select(.name == \"$2\").headers[] | [.name, .value] | @csv" ) | sed --expression 's/"//g' | sed --expression 's/\\//g' | sed --expression 's/,/: /g')
BODY=$(cat $1 | (jq ".requests[] | select(.name == \"$2\").body.raw")  | sed --expression 's/\\n//g' | sed --expression 's/\\//g' | sed --expression 's/^"//g' | sed --expression 's/"$//g')


echo "$METHOD $URL HTTP/1.1"
echo $HEADERS
echo

if [ "$BODY" != "null" ]; then
    echo $BODY
fi
