GET {{$dotenv %ENDPOINT}}/item HTTP/1.1
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjkyMzczOTAzLCJqdGkiOiIzN2JhNjEzMi04NWYzLTRjODktYTQxZi0yN2I4YWI3YmVhMjQiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE2OTIzNzM5MDMsImV4cCI6MTY5MjM3NDgwMywiaXNfYWRtaW4iOnRydWV9.YSs5MXRW_cp22KWd74B9TwhYbKVGE-fv2d_co1LzeTU"